apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-secrets
  namespace: monitoring
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: alertmanager-secrets
    creationPolicy: Owner
  data:
    - secretKey: slack_webhook
      remoteRef:
        key: alertmanager-slack_webhook 
    - secretKey: email_password
      remoteRef:
        key: alertmanager-email_app_password
