apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: ${GCP_PROJECT_ID}
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-secret-manager
            namespace: external-secrets
            key: key.json
