apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: GCP-Microsvc_App
  namespace: argocd
spec:
  description: Project for GCP Microservices
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'