apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: ingress
  namespace: argocd
spec:
  project: gcp-microsvc-app
  source: 
    repoURL: https://github.com/busybrainx99/GCP_Microsvc_App.git
    targetRevision: main
    path: ingress-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true