apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: nginx
  namespace: argocd
spec:
  project: GCP-Microsvc_App
  source: 
    repoURL: https://kubernetes.github.io/ingress-nginx
    helm:
      chart: ingress-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true