name: Cleanup GKE MicroSvc

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_NAME }} \
          --zone ${{ secrets.GKE_ZONE }} \
          --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Cleanup ArgoCD Applications
        run: |
          kubectl delete application --all -n argocd --ignore-not-found

      - name: Wait Before Terraform Destroy
        run: sleep 60
      
      - name: Destroy Terraform infrastructure
        run: |
          terraform init
          terraform destroy -auto-approve
        working-directory: terraform_code