name: Deploy GKE MicroSvc

on:
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Deploy Terraform infrastructure
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve
        working-directory: terraform_code
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_name: ${{ secrets.GKE_NAME }}
          TF_VAR_zone: ${{ secrets.GKE_ZONE }}
          TF_VAR_region: ${{ secrets.GKE_REGION }}
          TF_VAR_account_id: ${{ secrets.GKE_ACCOUNT_ID }}
          TF_VAR_config_path: ${{ secrets.GKE_CONFIG_PATH }}

      - name: Install gcloud SDK
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk

      - name: Install gke-gcloud-auth-plugin
        run: |
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
          gke-gcloud-auth-plugin --version

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Install helm
        uses: azure/setup-helm@v4.2.0
     
      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_NAME }} \
          --zone ${{ secrets.GKE_ZONE }} \
          --project ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Install External Secrets Operator
        run: |
          helm repo add external-secrets https://charts.external-secrets.io
          helm repo update external-secrets
          helm install external-secrets external-secrets/external-secrets \
            --namespace external-secrets \
            --create-namespace

      - name: Install envsubst
        run: sudo apt-get update && sudo apt-get install -y gettext-base

      - name: Create GCP secrets
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > key.json
          kubectl create secret generic gcp-secret-manager \
            --from-file=key.json=key.json \
            -n external-secrets
          rm key.json

      - name: Apply ClusterSecretStore
        run: |
          export GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
          envsubst < gcp-cluster-secret-store.yml | kubectl apply -f -
        
      - name: Apply Additional Configs
        run: |
          kubectl create namespace monitoring --dry-run=client -0 yaml | kubectl apply -f -
          kubectl apply -f alertmanager-external-secret.yml
        
      - name: Install ArgoCD
        run: |
          kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
          kubectl wait --for=condition=available deployment -l app.kubernetes.io/name=argocd-server -n argocd --timeout=300s

      - name: Apply Argo applications
        run: |
           kubectl apply -f argocd-manifest/microsvc.yml
           kubectl apply -f argocd-manifest/cert-manager.yml
           kubectl apply -f argocd-manifest/encrypt.yml
           kubectl apply -f argocd-manifest/prometheus-app.yml
           kubectl apply -f argocd-manifest/grafana.yml
           kubectl apply -f argocd-manifest/nginx-ingress.yml
           kubectl apply -f argocd-manifest/ingress.yml





